- job:
    name: 'qcs-PILOT-nightly-automation'
    node: 'f27-os'
    triggers:
        - timed: '@midnight'
    scm:
        - git:
            url: https://github.com/quipucords/camayoc.git
            basedir: camayoc
            branches:
                - '*/master'
            skip-tag: true
    wrappers:
        - credentials-binding:
            - file:
                credential-id: 4c692211-c5e1-4354-8e1b-b9d0276c29d9
                variable: ID_JENKINS_RSA
        - ssh-agent-credentials:
            users:
                - '390bdc1f-73c6-457e-81de-9e794478e0e'
    builders:
        - config-file-provider:
            files:
              - file-id: '62cf0ccc-220e-4177-9eab-f39701bff8d7'
                target: 'camayoc/config.yaml'

        - shining-panda:
            build-environment: virtualenv
            python-version: System-CPython-3.6
            nature: shell
            command: |
                export XDG_CONFIG_HOME=$PWD
                mkdir -p /home/jenkins/.ssh
                cp "${ID_JENKINS_RSA}" /home/jenkins/.ssh/id_rsa
                chmod 0600 /home/jenkins/.ssh/id_rsa
                
                sed -i "s/{jenkins_slave_ip}/${OPENSTACK_PUBLIC_IP}/" camayoc/config.yaml

                echo "OPTIONS=--log-driver=journald" > docker.conf
                echo "DOCKER_CERT_PATH=/etc/docker" >> docker.conf
                sudo cp docker.conf /etc/sysconfig/docker
                sudo systemctl start docker
                echo "load docker container from tarball"
                curl -k -O -sSL https://github.com/quipucords/quipucords/releases/download/0.0.41-pilot/quipucords.0.0.41.tar.gz
                sudo docker load -i ${WORKSPACE}/quipucords.0.0.41.tar.gz

                # make log dir to save server logs
                mkdir ${WORKSPACE}/log
                # run docker container, mounting local volumes for logs and ssh keys
                sudo docker run -d -p "443:443" -v /tmp:/tmp -v /home/jenkins/.ssh:/home/jenkins/.ssh -v ${WORKSPACE}/log:/var/log -i "quipucords:0.0.41"

                # Install qpc from rpm
                sudo wget -O /etc/yum.repos.d/group_quipucords-qpc-fedora-27.repo https://copr.fedorainfracloud.org/coprs/g/quipucords/qpc/repo/fedora-27/group_quipucords-qpc-fedora-27.repo
                # build specific qpc package for pilot
                sudo dnf -y install qpc-0.0.41-1.git.574.87a6e52.fc27

                # create pytest configuration file to ignore the insecure
                # requests warnings that talking to the server over https
                # without a good cert cause
                cat >> pytest.ini << EOF
                [pytest]
                filterwarnings = ignore::urllib3.exceptions.InsecureRequestWarning
                EOF

                # Install camayoc and run test suite
                pip install ./camayoc[dev]

                set +e
                py.test -c pytest.ini -v --junit-xml ${WORKSPACE}/junit.xml camayoc/camayoc/tests/qcs/
                set -e  
                # Archive server logs to aid in analyzing test failures
                cd ${WORKSPACE}
                tar -cvzf server-logs.tar.gz ${WORKSPACE}/log
    publishers:
        - junit:
            results: junit.xml
        - archive:
            artifacts: 'server-logs.tar.gz'
            allow-empty: false
        - mark-node-offline
