- job:
    name: 'qcs-nightly-automation'
    node: 'f25-os'
    triggers:
        - timed: '@midnight'
    scm:
        - git:
            url: https://github.com/quipucords/camayoc.git
            basedir: camayoc
            branches:
                - '*/master'
            skip-tag: true
        - git:
            url: https://github.com/quipucords/quipucords.git
            basedir: quipucords
            branches:
                - '*/master'
            skip-tag: true
    wrappers:
        - ssh-agent-credentials:
            users:
                - '390bdc1f-73c6-457e-81de-9e794478e0e'
    builders:
        - config-file-provider:
            files:
              - file-id: '2c2b5dc8-3794-4d62-b49a-c3968cd5843a'
                target: 'camayoc/config.yaml'
        - shell: |
            sudo dnf install -y python36
        - shining-panda:
            build-environment: virtualenv
            python-version: System-CPython-3.6
            nature: shell
            command: |
                export XDG_CONFIG_HOME=$PWD
                mkdir -p /home/jenkins/.ssh
                touch /home/jenkins/.ssh/id_rsa
                chmod 0600 /home/jenkins/.ssh/id_rsa
                cd quipucords
                sudo dnf install -y python-tools
                pip install -r requirements.txt
                make server-init
                # run server in background and collect its PID
                nohup make serve > $WORKSPACE/server.log 2>&1 &
                export SERVERPID=$!

                cd -
                pip install ./camayoc[dev]

                set +e
                py.test -v --junit-xml ${WORKSPACE}/junit.xml camayoc/camayoc/tests/qcs
                set -e

                # kill the server running in the background
                kill -n 9 $SERVERPID

    publishers:
        - junit:
            results: junit.xml
        - archive:
            artifacts: 'server.log'
            allow-empty: 'true'
        - mark-node-offline
