- job:
    name: 'rho-nightly-automation'
    node: 'f25-np'
    triggers:
        - timed: '@midnight'
    scm:
        - git:
            url: https://github.com/quipucords/camayoc.git
            basedir: camayoc
            branches:
                - '*/master'
            skip-tag: true
        - git:
            url: https://github.com/quipucords/rho.git
            basedir: rho
            branches:
                - '*/master'
            skip-tag: true
    wrappers:
        - ssh-agent-credentials:
            users:
                - '390bdc1f-73c6-457e-81de-9e794478e0e'
    builders:
        - shining-panda:
            build-environment: virtualenv
            python-version: System-CPython-3
            nature: shell
            command: |
                cd rho
                pip install -r requirements.txt
                cd -
                pip install ./camayoc[dev]
                pip install pytest-xdist

                cat > .coveragerc <<EOF
                [run]
                concurrency=
                    multiprocessing
                    thread
                data_file=${PWD}/.coverage
                source=
                    ${PWD}/rho/rho
                EOF

                export COVERAGE_PROCESS_START="${PWD}/.coveragerc"
                RHO="$(which rho)"
                sed -i '/#!/a import coverage; coverage.process_startup()' "${RHO}"

                # Link RHO ansible modules
                sudo mkdir -p /usr/share/ansible/rho/
                sudo ln -s "${PWD}/rho/rho_playbook.yml" /usr/share/ansible/rho/
                sudo ln -s "${PWD}/rho/library" /usr/share/ansible/rho/
                sudo ln -s "${PWD}/rho/roles" /usr/share/ansible/rho/

                # Make sure the path $HOME/.ssh/id_rsa is a valid path in order
                # to not fail the rho auth validation for the sshkeypath. Even
                # though this will be an empty file, the SSH key used will come
                # from the ssh-agent.
                mkdir -p /home/jenkins/.ssh/
                touch /home/jenkins/.ssh/id_rsa

                set +e
                py.test -v -n auto --junit-xml junit.xml camayoc/camayoc/tests/rho
                set -e

                coverage combine
                coverage report
                coverage xml
    publishers:
        - junit:
            results: junit.xml
        - cobertura:
            fail-no-reports: true
            report-file: coverage.xml
            source-encoding: UTF_8
            targets:
                - line:
                    healthy: 80
                    unhealthy: 50
                    failing: 0
        - mark-node-offline
