- name: Create jenkins group.
  group:
    name: jenkins

- name: Create jenkins user.
  user:
    createhome: yes
    group: jenkins
    home: /home/jenkins
    name: jenkins
    password: $6$elD/JslzxlOEGtd9$DZ.EHUMyOta8UQW5Fqg5aJkNOOUL7.MpSNPXBrZHNFmiH7MfUOODQF.7i0RACHJc2hfd2oM1ClZIkIjGFQsL40

- name: Install ssh key for jenkins
  authorized_key:
    key: "{{ lookup('file', '{{ jenkins_public_key }}' ) }}"
    state: present
    user: jenkins
    manage_dir: yes

- name: Allow jenkins to run sudo commands without password.
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%jenkins\s'
    line: '%jenkins ALL=(ALL) NOPASSWD: ALL'

- name: Install custom repo file
  copy:
    src: "{{ lookup('file', '{{custom_repo_file}}' ) }}"
    dest: /etc/yum.repos.d/custom.repo
  when: custom_repo_file is defined

  #- name: Install epel
  #  yum_repository:
  #    name: epel
  #    description: EPEL YUM repo
  #    baseurl: "{{ epel_base_url }}"
  #    metalink: "{{ epel_metalink }}" 
  #    gpgcheck: false
  #  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version <= 7 

- name: Install required packages.
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - curl
      #    - docker
    - gcc
    - git
    - java
    - libffi-devel
#    - libselinux-python
    - openssl-devel
    - python36-devel
    - python3-pip
    - redhat-lsb-core
    - redhat-rpm-config
    - vim
    - wget
    - yum-utils
