- block:
  - name: Install packages required for jboss
    action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
    with_items:
      - unzip
      - java-1.8.0-openjdk-devel
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-headless

  - name: Ensure base dir that jboss will be installed into and log dir exists
    file:
      path: '{{item}}'
      state: directory
      owner: '{{jboss_username}}'
      group: '{{jboss_username}}'
      mode: 0755
    with_items:
        - '{{jboss_base_dir}}'
        - '{{jboss_log_dir}}'

  - name: Unpack jboss zip into base dir
    unarchive:
      copy: True
      src: '{{jboss_zip_path}}'
      dest: '{{jboss_base_dir}}/'
      group: '{{jboss_username}}'
      mode: "0644"
      owner: '{{jboss_username}}'
      list_files: True
    register: unzip_result

  - name: Set name of jboss install dir based on unzip task
    set_fact:
        jboss_install_dir: "{{jboss_base_dir}}/{{unzip_result['files'][0]}}"

  - debug:
      msg: install dir is now {{jboss_install_dir}}

  - name: Ensure jboss user can read all dirs
    command: 'find {{ jboss_install_dir }} -type d -exec chmod -c 0755 {} \;'

  - name: Make standalone.sh executable
    file:
        path: '{{jboss_install_dir}}/bin/standalone.sh'
        mode: 'u=rwx'
        state: 'touch'

  - name: Install standalone.conf file
    template:
        src: standalone.conf.j2
        dest: '/etc/default/{{jboss_service_name}}.conf'

  - name: Install systemd unit file
    template:
        src: jboss_eap.service.j2
        dest: '/usr/lib/systemd/system/{{jboss_service_name}}.service'

  - name: Run daemon reload
    shell: "systemctl daemon-reload"

  - name: Start services
    service: "name={{jboss_service_name}} state=started enabled=yes"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 6
