- hosts: all
  roles:
    - role: subscription-manager
      when: ansible_distribution == 'RedHat'
    - role: jboss_eap_install

# To use this playbook, provide the following variables:
# ansible-playbook -i /path/to/hosts jboss-eap-install.yaml \
# -e jboss_zip_path=/path/to/jboss-eap-7.0.0.zip
#
# You can register a RHEL 7 system with subscription manager by providing your
# username and password:
#
# -e rhn_username=USERNAME -e rhn_password=PASSWORD
#
# By providing the following variables, you can provide a custom rhsm server
# and base url to subscription-manager
#
# -e custom_baseurl=CDNURL \
# -e custom_server=SERVERURL \
#
# Other optional variables:
#
# systemd: BOOLEAN
#
#      By default, jboss is installed with chkconfig. If you prefer systemd,
#      pass -e '{systemd: true}'
#
# jboss_base_dir: PATH
#     The directory in which the zip file will be unpacked (parent eventual
#     to JBOSS_HOME i.e., where this jboss install will actually be)
# jboss_log_dir:
#     Path to the directory where jboss will put its logs. Can only be
#     specified when installing with systemd
#
# jboss_service_name: STRING
#     Name that the service will be called, i.e. what systemctl will know it as
#     Can only be specified when installing with systemd.
#
# jboss_user_dir: PATH
#     Home directory of jboss user
#
# jboss_username: STRING
#     Name of the jboss user, who will own the process running jboss
