---

# Playbooks should conditionally include this role by placing the following
# assertion into a `when:` statement.
- name: Ensure expected distribution
  assert:
    that: ansible_distribution == "RedHat"

# De-registering and then registering is equivalent to using the
# `force_register` argument, which was added in Ansible 2.2. We use this
# technique to preserve compatibility with RHEL 6.
- name: subscription-manager de-register
  redhat_subscription:
    state: absent
  when:
    - rhn_username is defined
    - rhn_password is defined

- name: Edit rhsm.conf
  shell: 'subscription-manager config --server.hostname {{custom_server}} --server.insecure 1 --rhsm.baseurl {{custom_baseurl}}'
  when:
      - custom_baseurl is defined
      - custom_server is defined

- name: subscription-manager register and subscribe by username and password
  redhat_subscription:
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    autosubscribe: True
  ignore_errors: yes
  when:
    - rhn_username is defined
    - rhn_password is defined

- name: Enable EPEL repository
  action: "{{ ansible_pkg_mgr }} name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
